version: '2'
volumes:
  grafana_data: {}
  prometheus: {}

networks:
  monitoring:
    driver: bridge

services:

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.13.1
    ports:
      - "9090:9090"
    tty: true
    command:
      - --config.file=/etc/prometheus.conf
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.conf:/etc/prometheus.conf
      - ./prometheus/alertrules.conf:/etc/alertrules.conf
    networks:
      - monitoring

  names-app:
    build: functions/.
    ports:
      - "9091:9091"
    tty: true
    stdin_open: true
    networks:
      - monitoring
